-- MySQL Script generated by MySQL Workbench
-- Sun Jan  6 14:39:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema payicam_ginger
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `payicam_ginger` ;

-- -----------------------------------------------------
-- Schema payicam_ginger
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `payicam_ginger` DEFAULT CHARACTER SET utf8 ;
USE `payicam_ginger` ;

-- -----------------------------------------------------
-- Table `payicam_ginger`.`administrateurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payicam_ginger`.`administrateurs` ;

CREATE TABLE IF NOT EXISTS `payicam_ginger`.`administrateurs` (
  `id` INT(11) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `nom` VARCHAR(55) NOT NULL,
  `prenom` VARCHAR(55) NOT NULL,
  `online` TINYINT(1) NOT NULL DEFAULT 0,
  `role_id` INT(2) NOT NULL DEFAULT 3,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC),
  INDEX `role_id` (`role_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `payicam_ginger`.`applications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payicam_ginger`.`applications` ;

CREATE TABLE IF NOT EXISTS `payicam_ginger`.`applications` (
  `app_id` INT(11) UNSIGNED NOT NULL COMMENT 'id interne de l\'application',
  `app_url` VARCHAR(255) NULL DEFAULT NULL COMMENT 'url du service autorisé',
  `app_key` CHAR(32) NOT NULL,
  `app_name` VARCHAR(100) NOT NULL,
  `app_desc` TEXT NULL DEFAULT NULL,
  `app_creator` VARCHAR(8) NOT NULL COMMENT 'Login de l\'utilisateur ayant crÃ©e la clef.',
  `app_lastuse` DATETIME NOT NULL COMMENT 'Date de la dernière utilisation de cette clef.',
  `app_created` DATETIME NOT NULL COMMENT 'Date de création de la clef',
  `app_removed` DATETIME NULL DEFAULT NULL COMMENT 'Est ce que la clef est supprimée.',
  PRIMARY KEY (`app_id`),
  UNIQUE INDEX `app_key` (`app_key` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Liste des applications et leurs clefs.';


-- -----------------------------------------------------
-- Table `payicam_ginger`.`configs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payicam_ginger`.`configs` ;

CREATE TABLE IF NOT EXISTS `payicam_ginger`.`configs` (
  `name` VARCHAR(255) NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `payicam_ginger`.`papercut_int_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payicam_ginger`.`papercut_int_users` ;

CREATE TABLE IF NOT EXISTS `payicam_ginger`.`papercut_int_users` (
  `Username` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(24) NOT NULL DEFAULT 'print',
  `Credit Balance` DOUBLE NOT NULL,
  `Restricted Status` VARCHAR(1) NOT NULL DEFAULT 'Y',
  `Full Name` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Department` VARCHAR(200) NOT NULL,
  `Office` VARCHAR(200) NOT NULL,
  `Card/ID Number` VARCHAR(100) NOT NULL,
  `Card/ID PIN` VARCHAR(20) NOT NULL,
  `Notes` TEXT NOT NULL,
  `Secondary Card/ID Number` VARCHAR(100) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `payicam_ginger`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payicam_ginger`.`roles` ;

CREATE TABLE IF NOT EXISTS `payicam_ginger`.`roles` (
  `id` INT(2) NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `slug` VARCHAR(60) NOT NULL,
  `level` INT(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `payicam_ginger`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payicam_ginger`.`users` ;

CREATE TABLE IF NOT EXISTS `payicam_ginger`.`users` (
  `id_icam` INT(11) NULL DEFAULT NULL,
  `site` VARCHAR(55) NULL DEFAULT NULL,
  `login` VARCHAR(105) NOT NULL DEFAULT '',
  `nom` VARCHAR(55) NULL DEFAULT NULL,
  `prenom` VARCHAR(55) NULL DEFAULT NULL,
  `mail` VARCHAR(105) NOT NULL,
  `promo` INT(5) NOT NULL DEFAULT 0,
  `filiere` VARCHAR(55) NOT NULL DEFAULT 'Ingenieur',
  `badge_uid` VARCHAR(20) NULL DEFAULT NULL,
  `expiration_badge` DATE NULL DEFAULT NULL,
  `naissance` DATE NULL DEFAULT NULL,
  `sexe` TINYINT(1) NOT NULL DEFAULT 1,
  `img_link` VARCHAR(255) NOT NULL,
  `date_creation` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`login`),
  UNIQUE INDEX `mail` (`mail` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `payicam_ginger`.`applications`
-- -----------------------------------------------------
START TRANSACTION;
USE `payicam_ginger`;
INSERT INTO `payicam_ginger`.`applications` (`app_id`, `app_url`, `app_key`, `app_name`, `app_desc`, `app_creator`, `app_lastuse`, `app_created`, `app_removed`) VALUES (1, 'https://payicam.icam.fr/server/web/', 'XQQm1q2hEyfoMsyW', 'server', 'server de PayIcam', 'Antoine', '2014-05-24 00:00:00', '2014-05-24 00:00:00', 'NULL');
INSERT INTO `payicam_ginger`.`applications` (`app_id`, `app_url`, `app_key`, `app_name`, `app_desc`, `app_creator`, `app_lastuse`, `app_created`, `app_removed`) VALUES (2, 'https://payicam.icam.fr/admin_ginger', 'rB9KV0UoTLsFZoyy', 'admin_ginger', 'Appli Web gérant Ginger', 'Antoine', '2014-05-28 00:00:00', '2014-05-28 00:00:00', 'NULL');
INSERT INTO `payicam_ginger`.`applications` (`app_id`, `app_url`, `app_key`, `app_name`, `app_desc`, `app_creator`, `app_lastuse`, `app_created`, `app_removed`) VALUES (3, 'https://payicam.icam.fr/shotgunicam/', 'VzT4bjHGcmst4j7V', 'Shotgun PayIcam', 'Shotgun PayIcam', 'Antoine', '2014-05-31 00:00:00', '2014-05-31 00:00:00', 'NULL');
INSERT INTO `payicam_ginger`.`applications` (`app_id`, `app_url`, `app_key`, `app_name`, `app_desc`, `app_creator`, `app_lastuse`, `app_created`, `app_removed`) VALUES (4, 'https://payicam.icam.fr/spring_festival', 'gkGSY9PvBEJqDyi2', 'Spring Festival', 'Spring Festival', '', '2017-03-30 00:00:00', '2017-03-30 00:00:00', 'NULL');

COMMIT;


-- -----------------------------------------------------
-- Data for table `payicam_ginger`.`configs`
-- -----------------------------------------------------
START TRANSACTION;
USE `payicam_ginger`;
INSERT INTO `payicam_ginger`.`configs` (`name`, `value`) VALUES ('authentification', '1');
INSERT INTO `payicam_ginger`.`configs` (`name`, `value`) VALUES ('contact', 'contact.payicam@gmail.com');
INSERT INTO `payicam_ginger`.`configs` (`name`, `value`) VALUES ('inscriptions', '');
INSERT INTO `payicam_ginger`.`configs` (`name`, `value`) VALUES ('maintenance', '0');
INSERT INTO `payicam_ginger`.`configs` (`name`, `value`) VALUES ('websitename', 'Admin Ginger');

COMMIT;


-- -----------------------------------------------------
-- Data for table `payicam_ginger`.`roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `payicam_ginger`;
INSERT INTO `payicam_ginger`.`roles` (`id`, `name`, `slug`, `level`) VALUES (1, 'Administrateur', 'admin', 2);
INSERT INTO `payicam_ginger`.`roles` (`id`, `name`, `slug`, `level`) VALUES (2, 'Membre', 'member', 1);
INSERT INTO `payicam_ginger`.`roles` (`id`, `name`, `slug`, `level`) VALUES (3, 'Non inscrit', 'non-inscrit', 0);

COMMIT;

